from .user_crud import user
from .hero_crud import hero
from .team_crud import team
from .role_crud import role
from .group_crud import group
from .power_crud import power
from .weapon_crud import weapon
from .attivita_crud import attivita
from .impresa_crud import impresa
from .anagrafe_crud import anagrafe
from .comune_crud import comune
from .ateco_crud import ateco