"""tabelle

Revision ID: 31e4fec2b052
Revises: e3174b6be9e0
Create Date: 2022-11-02 17:20:25.067292

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '31e4fec2b052'
down_revision = 'e3174b6be9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('richiedente', sa.Column('piva', sa.String(length=11), nullable=True), schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('richiedente', 'piva', schema='edilizia')
    # ### end Alembic commands ###
