"""tabelle

Revision ID: ebf05496ade0
Revises: 6dd658cfb524
Create Date: 2022-11-08 16:37:41.197297

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'ebf05496ade0'
down_revision = '6dd658cfb524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
