"""tabelle

Revision ID: 81ec11add7e9
Revises: 55c588525ab2
Create Date: 2022-11-08 17:31:07.025364

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '81ec11add7e9'
down_revision = '55c588525ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('delegato_istanza_id_fkey', 'delegato', schema='edilizia', type_='foreignkey')
    op.create_foreign_key(None, 'delegato', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delegato', schema='edilizia', type_='foreignkey')
    op.create_foreign_key('delegato_istanza_id_fkey', 'delegato', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia', ondelete='CASCADE')
    # ### end Alembic commands ###
