"""tabelle

Revision ID: 1915894141ca
Revises: 93acbd1e3be7
Create Date: 2022-11-03 12:26:24.889363

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1915894141ca'
down_revision = '93acbd1e3be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkgroupuser', 'updated_at', schema='admin')
    op.drop_column('linkgroupuser', 'created_at', schema='admin')
    op.drop_column('linkistanzapratica', 'updated_at', schema='edilizia')
    op.drop_column('linkistanzapratica', 'created_at', schema='edilizia')
    op.drop_column('linkistanzauser', 'updated_at', schema='edilizia')
    op.drop_column('linkistanzauser', 'created_at', schema='edilizia')
    op.drop_column('linkpraticauser', 'updated_at', schema='edilizia')
    op.drop_column('linkpraticauser', 'created_at', schema='edilizia')
    op.drop_column('ingredient', 'updated_at', schema='ricette')
    op.drop_column('ingredient', 'created_at', schema='ricette')
    op.drop_column('linkrecipeingredient', 'updated_at', schema='ricette')
    op.drop_column('linkrecipeingredient', 'created_at', schema='ricette')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkrecipeingredient', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='ricette')
    op.add_column('linkrecipeingredient', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='ricette')
    op.add_column('ingredient', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='ricette')
    op.add_column('ingredient', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='ricette')
    op.add_column('linkpraticauser', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='edilizia')
    op.add_column('linkpraticauser', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='edilizia')
    op.add_column('linkistanzauser', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='edilizia')
    op.add_column('linkistanzauser', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='edilizia')
    op.add_column('linkistanzapratica', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='edilizia')
    op.add_column('linkistanzapratica', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='edilizia')
    op.add_column('linkgroupuser', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='admin')
    op.add_column('linkgroupuser', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='admin')
    # ### end Alembic commands ###
