"""tabelle

Revision ID: 7340f38c55d6
Revises: 2f6061ad28d2
Create Date: 2022-11-08 18:18:58.898711

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '7340f38c55d6'
down_revision = '2f6061ad28d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
