"""tabelle

Revision ID: 422892ab6680
Revises: 9dd221324bf6
Create Date: 2022-11-04 17:44:11.829911

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '422892ab6680'
down_revision = '9dd221324bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('istanza', sa.Column('ownersss', sa.ARRAY(sa.String()), nullable=True), schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('istanza', 'ownersss', schema='edilizia')
    # ### end Alembic commands ###
