"""tabelle

Revision ID: 670454c85f12
Revises: ddcacf543ab1
Create Date: 2022-11-11 18:15:29.187559

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '670454c85f12'
down_revision = 'ddcacf543ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagopa_importi',
    sa.Column('istanza_id', sa.Integer(), nullable=False),
    sa.Column('codimp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('importo', sa.Float(), nullable=True),
    sa.Column('causale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scadenza', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('azione', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['istanza_id'], ['edilizia.istanza.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='edilizia'
    )
    op.create_table('pagopa_pagamenti',
    sa.Column('istanza_id', sa.Integer(), nullable=False),
    sa.Column('codtrans', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('iuv', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('importo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('anagrafica', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('divisa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('esito', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metodo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uidriscossione', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['istanza_id'], ['edilizia.istanza.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='edilizia'
    )
    op.create_table('linkimportipagamenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importo_id', sa.Integer(), nullable=False),
    sa.Column('pagamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['importo_id'], ['edilizia.pagopa_importi.id'], ),
    sa.ForeignKeyConstraint(['pagamento_id'], ['edilizia.pagopa_pagamenti.id'], ),
    sa.PrimaryKeyConstraint('id', 'importo_id', 'pagamento_id'),
    schema='edilizia'
    )
    op.create_index(op.f('ix_edilizia_linkimportipagamenti_id'), 'linkimportipagamenti', ['id'], unique=False, schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edilizia_linkimportipagamenti_id'), table_name='linkimportipagamenti', schema='edilizia')
    op.drop_table('linkimportipagamenti', schema='edilizia')
    op.drop_table('pagopa_pagamenti', schema='edilizia')
    op.drop_table('pagopa_importi', schema='edilizia')
    # ### end Alembic commands ###
