"""tabelle

Revision ID: 55c588525ab2
Revises: 94415ccde770
Create Date: 2022-11-08 17:00:46.252280

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '55c588525ab2'
down_revision = '94415ccde770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('civico_istanza_id_fkey', 'civico', schema='edilizia', type_='foreignkey')
    op.create_foreign_key(None, 'civico', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia', ondelete='CASCADE')
    op.drop_constraint('domicilio_richiedente_id_fkey', 'domicilio', schema='edilizia', type_='foreignkey')
    op.create_foreign_key(None, 'domicilio', 'richiedente', ['richiedente_id'], ['id'], source_schema='edilizia', referent_schema='edilizia', ondelete='CASCADE')
    op.drop_constraint('giuridica_richiedente_id_fkey', 'giuridica', schema='edilizia', type_='foreignkey')
    op.create_foreign_key(None, 'giuridica', 'richiedente', ['richiedente_id'], ['id'], source_schema='edilizia', referent_schema='edilizia', ondelete='CASCADE')
    op.drop_constraint('mappale_nceu_istanza_id_fkey', 'mappale_nceu', schema='edilizia', type_='foreignkey')
    op.create_foreign_key(None, 'mappale_nceu', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia', ondelete='CASCADE')
    op.drop_constraint('mappale_nct_istanza_id_fkey', 'mappale_nct', schema='edilizia', type_='foreignkey')
    op.create_foreign_key(None, 'mappale_nct', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia', ondelete='CASCADE')
    op.drop_constraint('posizione_istanza_id_fkey', 'posizione', schema='edilizia', type_='foreignkey')
    op.create_foreign_key(None, 'posizione', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia', ondelete='CASCADE')
    op.drop_constraint('richiedente_istanza_id_fkey', 'richiedente', schema='edilizia', type_='foreignkey')
    op.create_foreign_key(None, 'richiedente', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia', ondelete='CASCADE')
    op.drop_constraint('tecnico_istanza_id_fkey', 'tecnico', schema='edilizia', type_='foreignkey')
    op.create_foreign_key(None, 'tecnico', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia', ondelete='CASCADE')
    op.drop_constraint('uiu_istanza_id_fkey', 'uiu', schema='edilizia', type_='foreignkey')
    op.create_foreign_key(None, 'uiu', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uiu', schema='edilizia', type_='foreignkey')
    op.create_foreign_key('uiu_istanza_id_fkey', 'uiu', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia')
    op.drop_constraint(None, 'tecnico', schema='edilizia', type_='foreignkey')
    op.create_foreign_key('tecnico_istanza_id_fkey', 'tecnico', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia')
    op.drop_constraint(None, 'richiedente', schema='edilizia', type_='foreignkey')
    op.create_foreign_key('richiedente_istanza_id_fkey', 'richiedente', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia')
    op.drop_constraint(None, 'posizione', schema='edilizia', type_='foreignkey')
    op.create_foreign_key('posizione_istanza_id_fkey', 'posizione', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia')
    op.drop_constraint(None, 'mappale_nct', schema='edilizia', type_='foreignkey')
    op.create_foreign_key('mappale_nct_istanza_id_fkey', 'mappale_nct', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia')
    op.drop_constraint(None, 'mappale_nceu', schema='edilizia', type_='foreignkey')
    op.create_foreign_key('mappale_nceu_istanza_id_fkey', 'mappale_nceu', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia')
    op.drop_constraint(None, 'giuridica', schema='edilizia', type_='foreignkey')
    op.create_foreign_key('giuridica_richiedente_id_fkey', 'giuridica', 'richiedente', ['richiedente_id'], ['id'], source_schema='edilizia', referent_schema='edilizia')
    op.drop_constraint(None, 'domicilio', schema='edilizia', type_='foreignkey')
    op.create_foreign_key('domicilio_richiedente_id_fkey', 'domicilio', 'richiedente', ['richiedente_id'], ['id'], source_schema='edilizia', referent_schema='edilizia')
    op.drop_constraint(None, 'civico', schema='edilizia', type_='foreignkey')
    op.create_foreign_key('civico_istanza_id_fkey', 'civico', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia')
    # ### end Alembic commands ###
