"""tabelle

Revision ID: d75a2700dfac
Revises: 31e4fec2b052
Create Date: 2022-11-02 17:26:44.722723

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'd75a2700dfac'
down_revision = '31e4fec2b052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
