"""tabelle

Revision ID: 54d9e95774a2
Revises: dcf6cfdaa2b3
Create Date: 2022-11-04 17:46:53.441075

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '54d9e95774a2'
down_revision = 'dcf6cfdaa2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
