"""tabelle

Revision ID: 93acbd1e3be7
Revises: 0884c91eef62
Create Date: 2022-11-03 12:18:00.607836

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '93acbd1e3be7'
down_revision = '0884c91eef62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
