"""tabelle

Revision ID: e3174b6be9e0
Revises: f6f0843ad377
Create Date: 2022-11-02 17:15:37.347938

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e3174b6be9e0'
down_revision = 'f6f0843ad377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giuridica',
    sa.Column('cf', sa.String(length=16), nullable=True),
    sa.Column('piva', sa.String(length=11), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pec', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cellulare', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fax', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comune', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prov', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('loc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cap', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('indirizzo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('civico', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('denominazione', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('richiedente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['richiedente_id'], ['edilizia.richiedente.id'], ),
    sa.PrimaryKeyConstraint('id', 'richiedente_id'),
    schema='edilizia'
    )
    op.add_column('richiedente', sa.Column('principale', sa.Boolean(), nullable=True), schema='edilizia')
    op.add_column('richiedente', sa.Column('sostituto', sa.Boolean(), nullable=True), schema='edilizia')
    op.drop_column('richiedente', 'piva', schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('richiedente', sa.Column('piva', sa.VARCHAR(length=11), autoincrement=False, nullable=True), schema='edilizia')
    op.drop_column('richiedente', 'sostituto', schema='edilizia')
    op.drop_column('richiedente', 'principale', schema='edilizia')
    op.drop_table('giuridica', schema='edilizia')
    # ### end Alembic commands ###
