"""tabelle

Revision ID: 1a28f36f4959
Revises: d5f04bf474bb
Create Date: 2022-11-04 16:02:43.379224

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '1a28f36f4959'
down_revision = 'd5f04bf474bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delegato', sa.Column('qualita', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='edilizia')
    op.add_column('delegato', sa.Column('search', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='edilizia')
    op.add_column('giuridica', sa.Column('qualita', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='edilizia')
    op.add_column('giuridica', sa.Column('qualita_altro', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='edilizia')
    op.add_column('istanza', sa.Column('data_creazione', sa.DateTime(timezone=True), nullable=True), schema='edilizia')
    op.add_column('istanza', sa.Column('tipo_altro', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='edilizia')
    op.add_column('richiedente', sa.Column('qualita', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='edilizia')
    op.add_column('richiedente', sa.Column('search', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('richiedente', 'search', schema='edilizia')
    op.drop_column('richiedente', 'qualita', schema='edilizia')
    op.drop_column('istanza', 'tipo_altro', schema='edilizia')
    op.drop_column('istanza', 'data_creazione', schema='edilizia')
    op.drop_column('giuridica', 'qualita_altro', schema='edilizia')
    op.drop_column('giuridica', 'qualita', schema='edilizia')
    op.drop_column('delegato', 'search', schema='edilizia')
    op.drop_column('delegato', 'qualita', schema='edilizia')
    # ### end Alembic commands ###
