"""tabelle

Revision ID: e7031677f289
Revises: 90b8c0c6a726
Create Date: 2022-11-07 10:44:42.243916

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e7031677f289'
down_revision = '90b8c0c6a726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('domicilio_richiedente_id_fkey', 'domicilio', schema='edilizia', type_='foreignkey')
    op.create_foreign_key(None, 'domicilio', 'richiedente', ['richiedente_id'], ['id'], source_schema='edilizia', referent_schema='edilizia')
    op.drop_constraint('giuridica_richiedente_id_fkey', 'giuridica', schema='edilizia', type_='foreignkey')
    op.create_foreign_key(None, 'giuridica', 'richiedente', ['richiedente_id'], ['id'], source_schema='edilizia', referent_schema='edilizia')
    op.add_column('istanza', sa.Column('readers', sa.ARRAY(sa.String()), nullable=True), schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('istanza', 'readers', schema='edilizia')
    op.drop_constraint(None, 'giuridica', schema='edilizia', type_='foreignkey')
    op.create_foreign_key('giuridica_richiedente_id_fkey', 'giuridica', 'richiedente', ['richiedente_id'], ['id'], source_schema='edilizia', referent_schema='edilizia', onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'domicilio', schema='edilizia', type_='foreignkey')
    op.create_foreign_key('domicilio_richiedente_id_fkey', 'domicilio', 'richiedente', ['richiedente_id'], ['id'], source_schema='edilizia', referent_schema='edilizia', onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
