"""tabelle

Revision ID: d5f04bf474bb
Revises: a5a534ac8d35
Create Date: 2022-11-03 15:52:13.640473

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'd5f04bf474bb'
down_revision = 'a5a534ac8d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delegato', 'id', schema='edilizia')
    op.drop_column('domicilio', 'id', schema='edilizia')
    op.drop_column('giuridica', 'id', schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giuridica', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False), schema='edilizia')
    op.add_column('domicilio', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False), schema='edilizia')
    op.add_column('delegato', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False), schema='edilizia')
    # ### end Alembic commands ###
