"""tabelle

Revision ID: d9e0395dd00d
Revises: 54d9e95774a2
Create Date: 2022-11-04 17:48:08.236737

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'd9e0395dd00d'
down_revision = '54d9e95774a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tecnico', 'ruolo', schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tecnico', sa.Column('ruolo', sa.VARCHAR(), autoincrement=False, nullable=True), schema='edilizia')
    # ### end Alembic commands ###
