"""tabelle

Revision ID: 271d342bb541
Revises: c8883bcaac9e
Create Date: 2022-11-08 09:52:21.891686

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '271d342bb541'
down_revision = 'c8883bcaac9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mappale_nceu',
    sa.Column('sezione', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('foglio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mappale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subaterno', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('istanza_id', sa.Integer(), nullable=False),
    sa.Column('sostituito', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['istanza_id'], ['edilizia.istanza.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='edilizia'
    )
    op.create_table('mappale_nct',
    sa.Column('geom_plg', Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('sezione', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('foglio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mappale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('istanza_id', sa.Integer(), nullable=False),
    sa.Column('sostituito', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['istanza_id'], ['edilizia.istanza.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='edilizia'
    )
    op.create_table('uiu',
    sa.Column('civico', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interno', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sezione', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('foglio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mappale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subaterno', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scala', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('piano', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vani', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supeficie', sa.Float(), nullable=True),
    sa.Column('destuso', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('istanza_id', sa.Integer(), nullable=False),
    sa.Column('sostituito', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['istanza_id'], ['edilizia.istanza.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='edilizia'
    )
    op.add_column('civico', sa.Column('sostituito', sa.Boolean(), nullable=True), schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('civico', 'sostituito', schema='edilizia')
    op.drop_table('uiu', schema='edilizia')
    op.drop_index('idx_mappale_nct_geom_plg', table_name='mappale_nct', schema='edilizia', postgresql_using='gist')
    op.drop_table('mappale_nct', schema='edilizia')
    op.drop_table('mappale_nceu', schema='edilizia')
    # ### end Alembic commands ###
