"""tabelle

Revision ID: a5a534ac8d35
Revises: 1915894141ca
Create Date: 2022-11-03 12:36:19.214188

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'a5a534ac8d35'
down_revision = '1915894141ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True), schema='ricette')
    op.create_foreign_key(None, 'recipe', 'user', ['created_by_id'], ['id'], source_schema='ricette', referent_schema='admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', schema='ricette', type_='foreignkey')
    op.drop_column('recipe', 'created_by_id', schema='ricette')
    # ### end Alembic commands ###
