"""tabelle

Revision ID: 1d1c42cb28f5
Revises: 271d342bb541
Create Date: 2022-11-08 10:05:15.343953

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '1d1c42cb28f5'
down_revision = '271d342bb541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posizione',
    sa.Column('localita', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('coord_lng', sa.Float(), nullable=True),
    sa.Column('coord_lat', sa.Float(), nullable=True),
    sa.Column('coord_x', sa.Float(), nullable=True),
    sa.Column('coord_y', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('istanza_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['istanza_id'], ['edilizia.istanza.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='edilizia'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posizione', schema='edilizia')
    # ### end Alembic commands ###
