"""tabelle

Revision ID: c8c15321bb27
Revises: d75a2700dfac
Create Date: 2022-11-03 10:01:44.364107

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8c15321bb27'
down_revision = 'd75a2700dfac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegato',
    sa.Column('cf', sa.String(length=16), nullable=True),
    sa.Column('piva', sa.String(length=11), nullable=True),
    sa.Column('codcat_nato', sa.String(length=4), nullable=True),
    sa.Column('sesso', sa.String(length=1), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pec', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cellulare', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fax', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comune', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prov', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('loc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cap', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('indirizzo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('civico', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('app', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cognome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_nato', sa.Date(), nullable=True),
    sa.Column('comune_nato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prov_nato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('loc_nato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cittadinanza', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('istanza_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['istanza_id'], ['edilizia.istanza.id'], ),
    sa.PrimaryKeyConstraint('id', 'istanza_id'),
    schema='edilizia'
    )
    op.add_column('richiedente', sa.Column('sostituito', sa.Boolean(), nullable=True), schema='edilizia')
    op.alter_column('richiedente', 'sesso',
               existing_type=postgresql.ENUM('M', 'F', name='sessotype'),
               type_=sa.String(length=1),
               existing_nullable=True,
               schema='edilizia')
    op.drop_column('richiedente', 'sostituto', schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('richiedente', sa.Column('sostituto', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='edilizia')
    op.alter_column('richiedente', 'sesso',
               existing_type=sa.String(length=1),
               type_=postgresql.ENUM('M', 'F', name='sessotype'),
               existing_nullable=True,
               schema='edilizia')
    op.drop_column('richiedente', 'sostituito', schema='edilizia')
    op.drop_table('delegato', schema='edilizia')
    # ### end Alembic commands ###
