"""tabelle

Revision ID: 8a5922c75a93
Revises: aced360c2dcc
Create Date: 2022-11-07 11:34:11.867241

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a5922c75a93'
down_revision = 'aced360c2dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('istanza', sa.Column('authors', sa.ARRAY(sa.String()), nullable=True), schema='edilizia')
    op.drop_column('istanza', 'owners', schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('istanza', sa.Column('owners', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True), schema='edilizia')
    op.drop_column('istanza', 'authors', schema='edilizia')
    # ### end Alembic commands ###
