"""tabelle

Revision ID: 90b8c0c6a726
Revises: 386bdc605229
Create Date: 2022-11-05 11:14:15.262851

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '90b8c0c6a726'
down_revision = '386bdc605229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
