"""tabelle

Revision ID: e06e6c36bab4
Revises: 0db45971d7fb
Create Date: 2022-11-07 11:27:42.837194

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e06e6c36bab4'
down_revision = '0db45971d7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
