"""tabelle

Revision ID: e2122dbb36e9
Revises: 
Create Date: 2022-11-10 17:04:10.490162

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'e2122dbb36e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giuridica', 'id', schema='edilizia')
    op.drop_column('domicilio', 'id', schema='edilizia')
    # ### end Alembic commands ###
