"""tabelle

Revision ID: 6d1bc12d31c8
Revises: 613383000a75
Create Date: 2022-11-07 11:46:53.433296

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '6d1bc12d31c8'
down_revision = '613383000a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tecnico', 'qualita', schema='edilizia')
    op.drop_column('tecnico', 'qualita_altro', schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tecnico', sa.Column('qualita_altro', sa.VARCHAR(), autoincrement=False, nullable=True), schema='edilizia')
    op.add_column('tecnico', sa.Column('qualita', sa.VARCHAR(), autoincrement=False, nullable=True), schema='edilizia')
    # ### end Alembic commands ###
