"""tabelle

Revision ID: 471f2aa007cd
Revises: 89b1dcf51502
Create Date: 2022-11-07 11:02:48.211768

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '471f2aa007cd'
down_revision = '89b1dcf51502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
