"""tabelle

Revision ID: 89b1dcf51502
Revises: 5acc9346f50b
Create Date: 2022-11-07 11:02:35.589622

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '89b1dcf51502'
down_revision = '5acc9346f50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
