"""tabelle

Revision ID: f6f0843ad377
Revises: b8318f11723b
Create Date: 2022-11-02 16:51:07.126625

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'f6f0843ad377'
down_revision = 'b8318f11723b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('richiedente', sa.Column('istanza_id', sa.Integer(), nullable=False), schema='edilizia')
    op.create_foreign_key(None, 'richiedente', 'istanza', ['istanza_id'], ['id'], source_schema='edilizia', referent_schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'richiedente', schema='edilizia', type_='foreignkey')
    op.drop_column('richiedente', 'istanza_id', schema='edilizia')
    # ### end Alembic commands ###
