"""tabelle

Revision ID: 0db45971d7fb
Revises: 471f2aa007cd
Create Date: 2022-11-07 11:27:07.719639

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0db45971d7fb'
down_revision = '471f2aa007cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('istanza', sa.Column('ownersss', sa.ARRAY(sa.String()), nullable=True), schema='edilizia')
    op.drop_column('istanza', 'owners', schema='edilizia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('istanza', sa.Column('owners', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True), schema='edilizia')
    op.drop_column('istanza', 'ownersss', schema='edilizia')
    # ### end Alembic commands ###
